### ISSUE TITLE
Still 502 Bad Gateway 

### ISSUE THREAD

**Issue by Kevi-Saikou** [tengyifei/openshift-cartridge-nginx-hhvm#14] opened 2015-03-06 04:22 UTC
nginx_error.log
2015/03/05 12:10:13 [error] 373279#0: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.143.222.115, server: v-kiz.rhcloud.com, request: "HEAD / HTTP/1.1", upstream: "fastcgi://unix:/var/lib/openshift/54f8888ee0b8cd1031000045/app-root/data/hhvm.sock:", host: "v-kiz.rhcloud.com"
2015/03/05 12:10:13 [error] 373279#0: *3 connect() to unix:/var/lib/openshift/54f8888ee0b8cd1031000045/app-root/data/hhvm.sock failed (111: Connection refused) while connecting to upstream, client: 10.143.222.115, server: v-kiz.rhcloud.com, request: "HEAD / HTTP/1.1", upstream: "fastcgi://unix:/var/lib/openshift/54f8888ee0b8cd1031000045/app-root/data/hhvm.sock:", host: "v-kiz.rhcloud.com"
2015/03/05 13:10:11 [error] 373279#0: *5 connect() to unix:/var/lib/openshift/54f8888ee0b8cd1031000045/app-root/data/hhvm.sock failed (111: Connection refused) while connecting to upstream, client: 10.143.222.115, server: v-kiz.rhcloud.com, request: "HEAD / HTTP/1.1", upstream: "fastcgi://unix:/var/lib/openshift/54f8888ee0b8cd1031000045/app-root/data/hhvm.sock:", host: "v-kiz.rhcloud.com"

我一直在创建新的Application并安装最新版的Cartridge，但它一直提示错误502。望修复，谢谢

**Comment by tengyifei** [comment] 2015-03-06 19:05
Looks like HHVM crashed in the middle of a request. Can you post the hhvm
log file as well? It's in the log folder.

**Comment by Kevi-Saikou** [comment] 2015-03-07 02:53
This is the hhvm.log in /nginx-hhvm/logs

Core dumped: Segmentation fault
Stack trace in /tmp/stacktrace.274064.log

Here is the hhvm trace log(/tmp/stacktrace.274064.log):
Host: ex-std-node318.prod.rhcloud.com
ProcessID: 275298
ThreadID: 7f97b89ff700
ThreadPID: 284845
Name: /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.5.0-0-ga90f4733cfa0d8fefdafc7433f758f78cdc75424
DebuggerCount: 0

ThreadType: Web Request
Server_SERVER_NAME: v-kiz.rhcloud.com
Server: v-kiz.rhcloud.com
URL: /

# 0  __restore_rt at sigaction.c:0
# 1  HPHP::MySQL::GetConn(HPHP::Variant const&, std::shared_ptr<HPHP::MySQL>*) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 2  HPHP::f_mysql_get_server_info(HPHP::Variant const&) at ext_mysql.cpp:0
# 3  void HPHP::Native::callFunc<true, false>(HPHP::Func const*, void*, HPHP::TypedValue*, HPHP::TypedValue&) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 4  void HPHP::ExecutionContext::dispatchImpl<false>() at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 5  HPHP::ExecutionContext::enterVM(HPHP::ActRec*, HPHP::ExecutionContext::StackArgsState, HPHP::Resumable*, HPHP::ObjectData*) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 6  HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, HPHP::Func const*, HPHP::Variant const&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 7  HPHP::ExecutionContext::invokeUnit(HPHP::TypedValue*, HPHP::Unit const*) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 8  HPHP::include_impl_invoke(HPHP::String const&, bool, char const*) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 9  HPHP::hphp_invoke(HPHP::ExecutionContext*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, HPHP::Array const&, HPHP::VRefParamValue const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool, bool) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 10 HPHP::HttpRequestHandler::executePHPRequest(HPHP::Transport*, HPHP::RequestURI&, HPHP::SourceRootInfo&, bool) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 11 HPHP::HttpRequestHandler::handleRequest(HPHP::Transport*) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 12 HPHP::ServerWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::FastCGITransportTraits>::doJobImpl(std::shared_ptr<HPHP::FastCGIJob>, bool) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 13 HPHP::JobQueueWorker<std::shared_ptr<HPHP::FastCGIJob>, HPHP::Server*, true, false, HPHP::JobQueueDropVMStack>::start() at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 14 HPHP::AsyncFuncImpl::ThreadFunc(void*) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 15 HPHP::start_routine_wrapper(void*) at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/hhvm:0
# 16 start_thread at pthread_create.c:0
# 17 __clone at /var/lib/openshift/54fa65a3e0b8cd5c720000a8/nginx-hhvm/usr/bin/libc.so.6:0

PHP Stacktrace:

**Comment by tengyifei** [comment] 2015-03-07 16:38
You may have stumbled upon an insidious HHVM bug :disappointed: I'll file a bug report for you so that they can get it fixed hopefully in the next release. Can you provide more information e.g. does this happen every time you run a certain PHP command or does it only happen under special conditions? Are you using a popular CMS like WordPress or custom PHP script etc.

**Comment by Kevi-Saikou** [comment] 2015-03-10 03:44
I was just running a PHP Proberv, you can download it from:
http://www.yahei.net/
I have never try other PHP program, Sorry..

**Comment by Kevi-Saikou** [comment] 2015-03-10 06:24
I have installed WordPress, and it runs perfectly, at least for now. Thank you very much.

**Comment by tengyifei** [comment] 2015-03-13 23:57
This issue is caused by passing `null` to `mysql_get_server_info` and is fixed in HHVM 3.6.0. In a few days I'll update this cartridge and we can close the issue.

**Comment by tengyifei** [comment] 2015-03-18 21:05
Addressed in e7d24e6057156b86d7974f5383d2d772dab5dd80. Please try with latest version of this cartridge.

**Closed by tengyifei** 2015-03-18 21:05 UTC
Labels: bug
